#site properties
title: "Mukha SSG"
title_en: "Mukha SSG"
title_ru: "ГСС «Муха»"
motto: "Делай мухой!"
url: "https://example.site"
theme: basic
description: |-
  Быстрый и простой генератор статичных сайтов.
description_ru: |-
  Быстрый и простой генератор статических сайтов.
description_en: |-
  Quick and simple static site generator.
#default maximum length of the list;
#max number of entries on single page
#of multipage lists
list_length: 30

#tags...
tags_dir: "/tags"
tags_page: "/tags/index.html"

#RSS props
rss_uri: "/rss.xml"
atom_uri: "/atom.xml"
#max count of rss feed items
rss_length: 30
edit_cmd: gedit
js_api: true
search: true
keep_excerpts: true
search_lang: ["ru", "en"]
