#site properties
title: "Mukha SSG"
motto: "Делай мухой!"
url: "https://example.site"
theme: basic
description: |-
  The example site for Mukha SSG
  also experimental theme
  with some css
#default maximum length of the list;
#max number of entries on single page
#of multipage lists
list_length: 30

#tags...
tags_dir: "/tags"
tags_page: "/tags/index.html"

#RSS props
rss_uri: "/rss.xml"
#max count of rss feed items
rss_length: 30
